{{ if index .Values "certificate" "enabled" }}

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ph-api-v2-thieme-tls
  labels: {}
spec:
  secretName: ph-api-v2-thieme-tls
  duration: 2160h0m0s # 90d
  renewBefore: 360h0m0s # 15d
  usages:
    - server auth
  dnsNames:
    - {{ .Values.ingressRoute.tld }}
    {{ range $idx, $value := .Values.certificate.extraTlds }}
    - {{ $value | quote }}
    {{- end }}
  issuerRef:
    name: {{ .Values.certificate.certManager.issuerRef.name }}
    kind: {{ .Values.certificate.certManager.issuerRef.kind }}
  privateKey:
    rotationPolicy: Always

{{- end -}}