apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "referrer.fullname" . }}-environments-cm
data:
{{- range $key, $value := .Values.env.configmap }}
  {{ $value.name | upper }}: {{ $value.value | quote }}
{{- end }}  