apiVersion: keyhub.topicus.nl/v1alpha1
kind: KeyHubSecret
metadata:
  name: {{ include "eck.fullname" . }}-environments-secret
spec:
  data:
  {{- range $key, $value := .Values.env.keyhubVaultRecords }}
    - name: {{ $value.name | upper | quote }}
      record: {{ $value.record | quote }}
      property: {{ $value.property | quote }}
  {{- end }}