{{- if and .Values.certificate.enabled .Values.certificate.keyhubSecret.enabled }}
{{ fail "Usage of certmanager and keyhubsecret are mutually exclusive" }}
{{- end }}
{{ if index .Values "certificate" "enabled" }}

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ph-thieme-tls
  labels: {}
spec:
  secretName: ph-thieme-tls
  duration: 2160h0m0s # 90d
  renewBefore: 360h0m0s # 15d
  usages:
    - server auth
  dnsNames:
    - {{ .Values.ingressRoute.tld }}
    - ws.{{ .Values.ingressRoute.tld }}
    - api.{{ .Values.ingressRoute.tld }}
    - app.{{ .Values.ingressRoute.tld }}
    {{ range $idx, $value := .Values.certificate.extraTlds }}
    - {{ $value | quote }}
    {{- end }}
  issuerRef:
    name: {{ .Values.certificate.certManager.issuerRef.name }}
    kind: {{ .Values.certificate.certManager.issuerRef.kind }}
  privateKey:
    rotationPolicy: Always

{{- else if .Values.certificate.keyhubSecret.enabled }}
# doc: https://kb.topicus.education/docs/devops/kubernetes/keyhub/#using-a-single-keyhub-vault-record
apiVersion: keyhub.topicus.nl/v1alpha1
kind: KeyHubSecret
metadata:
  name: ph-thieme-tls
spec:
  template:
    type: kubernetes.io/tls
  data:
    - name: {{ .Values.certificate.keyhubSecret.type }}
      record: {{ .Values.certificate.keyhubSecret.record }}
{{- end -}}